# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/InstructuinFetch.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/IF_ID.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/UC.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/ID_EX.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/EX.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/EX_MEM.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/Unitatea_MEM.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/MEM_WB.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/Afisor_7_segmente.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/MPG.vhd}
  {C:/Users/Vladu/Desktop/AC/Vladut_Rad MIPS pipeline/MIPSpipeline/MIPSpipeline.srcs/sources_1/new/MIPS.vhd}
}
synth_design -top MIPS -part xc7a35tcpg236-1
write_checkpoint -noxdef MIPS.dcp
catch { report_utilization -file MIPS_utilization_synth.rpt -pb MIPS_utilization_synth.pb }
